config/routes.rb
Rails.application.routes.draw do  
  match 'w2ui/index',                  to: 'w2ui#index'           , via: [:get, :post]        
  #match '/adm/:model/lib/*pages',              to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:id/*pages',              to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:action/*pages',          to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:action/:id/*pages',      to: 'w2ui#file_assets'        , via: [:get, :post]
  scope '/adm' do
    get   '/acesso_restrito',                  to: 'adm#acesso_restrito'
    get   '/tempo_sessao',                     to: 'adm#tempo_sessao'       
    get   '/senha_trocada_com_sucesso',        to: 'adm#senha_trocada_com_sucesso'  
    match '/',                                 to: 'adm#login'            , via: [:get, :post]
    match '/painel',                           to: 'adm#painel'           , via: [:get, :post]
    match '/esqueceu_a_senha',                 to: 'adm#esqueceu_a_senha'     , via: [:get, :post]
    match '/codigo_verificacao',               to: 'adm#codigo_verificacao'     , via: [:get, :post]
    match '/trocar_senha',                     to: 'adm#trocar_senha'       , via: [:get, :post]
    match '/cadastre_se',                      to: 'adm#cadastre_se'        , via: [:get, :post]
  match '/politicas',                        to: 'politicas#index'        , via: [:get, :post]
  match '/perfis_usuarios',                  to: 'perfis_usuarios#index'      , via: [:get, :post]
    resources :usuarios
    resources :perfis
    resources :menus
    resources :sistemas
    resources :galeria_fotos
    resources :galeria_videos
    resources :noticias
    resources :noticia_fotos
    resources :noticia_videos
  end
  match '*pages',                              to: 'w2ui#file_assets'				, via: [:get, :post]
end

app/models/sistema.rb
class Sistema < ApplicationRecord
	def sistemas_permitidos_por_usuario(_usuario_id)
		return Sistema
				.select("sistemas.*")
				.joins("inner join politicas on(politicas.sistema_id=sistemas.id)")
				.joins("inner join perfis on(perfis.id=politicas.perfil_id)")
				.joins("inner join perfis_usuarios on(perfis_usuarios.perfil_id=perfis.id)")
				.joins("inner join usuarios on(usuarios.id=perfis_usuarios.usuario_id)")
				.where("politicas.ver and usuarios.id=0"+_usuario_id.to_s)
				.group("sistemas.id")
				.order("nome asc")
	end
end

app/controllers/sistemas_controller.rb
class SistemasController < ApplicationController
  before_action :set_sistema, only: [:show, :edit, :update, :destroy]

  # GET /sistemas
  # GET /sistemas.json
  def index
	@acesso=acesso(nil)
	@sistemas=nil
	if (params["Menu_id"].nil?)
		@sistemas = Sistema.all.page(params['page']).per(10)
	else
		@sistemas = Sistema.where(permisao_por_menu: true).page(params['page']).per(10)
	end
  end

  # GET /sistemas/1
  # GET /sistemas/1.json
  def show
	@acesso=acesso(nil)
  end

  # GET /sistemas/new
  def new
	@acesso=acesso(nil)
    @sistema = Sistema.new
  end

  # GET /sistemas/1/edit
  def edit
	@acesso=acesso(nil)
  end

  # POST /sistemas
  # POST /sistemas.json
  def create
	@acesso=acesso(nil)
    @sistema = Sistema.new(sistema_params)
    respond_to do |format|
      if @sistema.save
        format.html { redirect_to @sistema, notice: 'Sistema was successfully created.' }
        format.json { render :show, status: :created, location: @sistema }
      else
        format.html { render :new }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sistemas/1
  # PATCH/PUT /sistemas/1.json
  def update
	@acesso=acesso(nil)
    respond_to do |format|
      if @sistema.update(sistema_params)
        format.html { redirect_to @sistema, notice: 'Sistema was successfully updated.' }
        format.json { render :show, status: :ok, location: @sistema }
      else
        format.html { render :edit }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sistemas/1
  # DELETE /sistemas/1.json
  def destroy
	@acesso=acesso(nil)
    @sistema.destroy
    respond_to do |format|
      format.html { redirect_to sistemas_url, notice: 'Sistema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sistema
	  @acesso=acesso(nil)  	
      @sistema = Sistema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sistema_params
	  @acesso=acesso(nil)
      params.require(:sistema).permit(:nome)
    end
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/views/sistemas/_form.html.erb
<%= form_for @sistema, :html => { :class => "form-horizontal sistema" } do |f| %>

  <% if @sistema.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sistema.errors.count, "error") %> prohibited this sistema from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sistema.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
	  <%if(@acesso.politica.salvar)%>	
      <%= f.submit nil, :class => 'btn btn-primary' %>
	  <%end%>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sistemas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sistemas/edit.html.erb
<%- model_class = Sistema -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sistemas/index.html.erb
<%- model_class = Sistema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @sistemas.each do |sistema| %>
      <tr>
        <td><%= link_to sistema.id, sistema_path(sistema) %></td>
        <td><%= sistema.nome %></td>
        <td><%=l sistema.created_at %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @sistemas %>

app/views/sistemas/new.html.erb
<%- model_class = Sistema -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sistemas/show.html.erb
<%- model_class = Sistema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @sistema.nome %></dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
              sistemas_path, :class => 'btn btn-default'  %>
<%if(@acesso.politica.editar)%>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sistema_path(@sistema), :class => 'btn btn-default' %>
<%end%>		
<%if(@acesso.politica.excluir)%>	  
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sistema_path(@sistema),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<%end%>		