config/routes.rb
Rails.application.routes.draw do  
  match 'w2ui/index',                  to: 'w2ui#index'           , via: [:get, :post]        
  #match '/adm/:model/lib/*pages',              to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:id/*pages',              to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:action/*pages',          to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:action/:id/*pages',      to: 'w2ui#file_assets'        , via: [:get, :post]
  scope '/adm' do
    get   '/acesso_restrito',                  to: 'adm#acesso_restrito'
    get   '/tempo_sessao',                     to: 'adm#tempo_sessao'       
    get   '/senha_trocada_com_sucesso',        to: 'adm#senha_trocada_com_sucesso'  
    match '/',                                 to: 'adm#login'            , via: [:get, :post]
    match '/painel',                           to: 'adm#painel'           , via: [:get, :post]
    match '/esqueceu_a_senha',                 to: 'adm#esqueceu_a_senha'     , via: [:get, :post]
    match '/codigo_verificacao',               to: 'adm#codigo_verificacao'     , via: [:get, :post]
    match '/trocar_senha',                     to: 'adm#trocar_senha'       , via: [:get, :post]
    match '/cadastre_se',                      to: 'adm#cadastre_se'        , via: [:get, :post]
  match '/politicas',                        to: 'politicas#index'        , via: [:get, :post]
  match '/perfis_usuarios',                  to: 'perfis_usuarios#index'      , via: [:get, :post]
    resources :usuarios
    resources :perfis
    resources :menus
    resources :sistemas
    resources :galeria_fotos
    resources :galeria_videos
    resources :noticias
    resources :noticia_fotos
    resources :noticia_videos
  end
  match '*pages',                              to: 'w2ui#file_assets'				, via: [:get, :post]
end

app/models/noticia_foto.rb
class NoticiaFoto < ApplicationRecord
  belongs_to :Noticia
  has_attached_file :foto, styles: 		{ tela_cheia: "1024x768>",            grande: "640x480>",			media: "320x240>",			pequena: "160x120>", 			ico: "32x32#" },
					convert_options: 	{ tela_cheia: "-quality 75 -strip",   grande: "-quality 75 -strip", media: "-quality 75 -strip",pequena: "-quality 75 -strip", 	ico: "-quality 75 -strip"},
					default_url: "/assets/img/sem_foto.png"
  validates_attachment_content_type :foto, content_type: ['image/jpg', 'image/png'] ,size: {in: 0..10.megabytes }					
  #validates :foto, dimensions: { width:  160, height: 120 }
end

app/controllers/noticia_fotos_controller.rb
class NoticiaFotosController < ApplicationController
  before_action :set_noticia_foto, only: [:show, :edit, :update, :destroy]

  # GET /noticia_fotos
  # GET /noticia_fotos.json
  def index
    @acesso=acesso(nil)
    @noticia_fotos = NoticiaFoto.all
  end

  # GET /noticia_fotos/1
  # GET /noticia_fotos/1.json
  def show
  end

  # GET /noticia_fotos/new
  def new
    @acesso=acesso(nil)
    @noticia_foto = NoticiaFoto.new
  end

  # GET /noticia_fotos/1/edit
  def edit
  end

  # POST /noticia_fotos
  # POST /noticia_fotos.json
  def create
    @noticia=Noticia.where("id=0"+@noticia_foto.Noticia_id).first
    @acesso=acesso(@noticia.Menu_id)
    @noticia_foto = NoticiaFoto.new(noticia_foto_params)

    respond_to do |format|
      if @noticia_foto.save
        format.html { redirect_to @noticia_foto, notice: 'Noticia foto was successfully created.' }
        format.json { render :show, status: :created, location: @noticia_foto }
      else
        format.html { render :new }
        format.json { render json: @noticia_foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia_fotos/1
  # PATCH/PUT /noticia_fotos/1.json
  def update
    @noticia=Noticia.where("id=0"+@noticia_foto.Noticia_id).first
    @acesso=acesso(@noticia.Menu_id)
    respond_to do |format|
      if @noticia_foto.update(noticia_foto_params)
        format.html { redirect_to @noticia_foto, notice: 'Noticia foto was successfully updated.' }
        format.json { render :show, status: :ok, location: @noticia_foto }
      else
        format.html { render :edit }
        format.json { render json: @noticia_foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia_fotos/1
  # DELETE /noticia_fotos/1.json
  def destroy
    @noticia=Noticia.where("id=0"+@noticia_foto.Noticia_id).first
    @acesso=acesso(@noticia.Menu_id)
    @noticia_foto.destroy
    respond_to do |format|
      format.html { redirect_to noticia_fotos_url, notice: 'Noticia foto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticia_foto
      @noticia_foto = NoticiaFoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticia_foto_params
      params.require(:noticia_foto).permit(:nome, :descricao, :Noticia_id,:foto)
    end
end

app/helpers/noticia_fotos_helper.rb
module NoticiaFotosHelper
end

app/views/noticia_fotos/_form.html.erb
<%= form_for @noticia_foto, :html => { :class => "form-horizontal noticia_foto" } do |f| %>

  <% if @noticia_foto.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@noticia_foto.errors.count, "error") %> prohibited this noticia_foto from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @noticia_foto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Noticia_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :Noticia_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:Noticia_id) %>
  </div>
  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>
  <div class="form-group">
    <%= f.label :foto, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :foto,:id=>"fileselect", :class => 'form-control' %>
    </div>
    <%=f.error_span(:foto) %>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                noticia_fotos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/noticia_fotos/edit.html.erb
<%- model_class = NoticiaFoto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/noticia_fotos/index.html.erb
<%- model_class = NoticiaFoto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Noticia_id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:foto) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @noticia_fotos.each do |noticia_foto| %>
      <tr>
        <td><%= link_to noticia_foto.id, noticia_foto_path(noticia_foto) %></td>
        <td><%= Noticia.where("id=0"+noticia_foto.Noticia_id.to_s).first.try(:titulo)   %></td>
        <td><%= noticia_foto.nome %></td>
        <td><%= noticia_foto.descricao %></td>
        <td><%= image_tag noticia_foto.foto.url(:pequena), size: "160x120"%></td>  
        <td><%=l noticia_foto.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      noticia_foto_path(noticia_foto), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_noticia_foto_path(noticia_foto), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      noticia_foto_path(noticia_foto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_noticia_foto_path,
            :class => 'btn btn-primary' %>

app/views/noticia_fotos/new.html.erb
<%- model_class = NoticiaFoto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/noticia_fotos/show.html.erb
<%- model_class = NoticiaFoto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @noticia_foto.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @noticia_foto.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Noticia_id) %>:</strong></dt>
  <dd><%= @noticia_foto.Noticia_id %></dd>
  <td><%= image_tag @noticia_foto.foto.url(:pequena), size: "160x120"%></td>  
  <dd><%= @noticia_foto.foto_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              noticia_fotos_path, :class => 'btn btn-default'  %>
<%if(@acesso.politica.editar)%> 
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_noticia_foto_path(@noticia_foto), :class => 'btn btn-default' %>
<%end%>
<%if(@acesso.politica.excluir)%>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              noticia_foto_path(@noticia_foto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<%end%>