config/routes.rb
Rails.application.routes.draw do  
  match 'w2ui/index',                  to: 'w2ui#index'           , via: [:get, :post]        
  #match '/adm/:model/lib/*pages',              to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:id/*pages',              to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:action/*pages',          to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:action/:id/*pages',      to: 'w2ui#file_assets'        , via: [:get, :post]
  scope '/adm' do
    get   '/acesso_restrito',                  to: 'adm#acesso_restrito'
    get   '/tempo_sessao',                     to: 'adm#tempo_sessao'       
    get   '/senha_trocada_com_sucesso',        to: 'adm#senha_trocada_com_sucesso'  
    match '/',                                 to: 'adm#login'            , via: [:get, :post]
    match '/painel',                           to: 'adm#painel'           , via: [:get, :post]
    match '/esqueceu_a_senha',                 to: 'adm#esqueceu_a_senha'     , via: [:get, :post]
    match '/codigo_verificacao',               to: 'adm#codigo_verificacao'     , via: [:get, :post]
    match '/trocar_senha',                     to: 'adm#trocar_senha'       , via: [:get, :post]
    match '/cadastre_se',                      to: 'adm#cadastre_se'        , via: [:get, :post]
  match '/politicas',                        to: 'politicas#index'        , via: [:get, :post]
  match '/perfis_usuarios',                  to: 'perfis_usuarios#index'      , via: [:get, :post]
    resources :usuarios
    resources :perfis
    resources :menus
    resources :sistemas
    resources :galeria_fotos
    resources :galeria_videos
    resources :noticias
    resources :noticia_fotos
    resources :noticia_videos
  end
  match '*pages',                              to: 'w2ui#file_assets'				, via: [:get, :post]
end

app/models/galeria_video.rb
class GaleriaVideo < ApplicationRecord
  belongs_to :Menu
  def galeriaPermitirdaPorMenuUsuario(_usuario_id)
	return GaleriaVideo.select("galeria_videos.*,menus.nome as menu")
	.joins(:Menu)
	.joins("inner JOIN Politicas ON (Politicas.menu_id= menus.id)")
	.joins("inner JOIN perfis ON (politicas.perfil_id= perfis.id)")
	.joins("inner JOIN perfis_usuarios ON perfis_usuarios.perfil_id=perfis.id")
	.joins("inner JOIN usuarios on (usuarios.id=perfis_usuarios.usuario_id and usuarios.id=0"+_usuario_id.to_s+")")
  end
end

app/controllers/galeria_videos_controller.rb
class GaleriaVideosController < ApplicationController
  before_action :set_galeria_video, only: [:show, :edit, :update, :destroy]

  # GET /galeria_videos
  # GET /galeria_videos.json
  def index
	@acesso=acesso(nil)
    @galeria_videos = GaleriaVideo.new.galeriaPermitirdaPorMenuUsuario(session[:usuario_id])
  end

  # GET /galeria_videos/1
  # GET /galeria_videos/1.json
  def show
	@acesso=acesso(@galeria_video.Menu_id)
  end

  # GET /galeria_videos/new
  def new
	@acesso=acesso(nil)
	@menus = Menu.new.menusPorNivel(">",session[:usuario_id])	
    @galeria_video = GaleriaVideo.new
  end

  # GET /galeria_videos/1/edit
  def edit
	@acesso=acesso(@galeria_video.Menu_id)
	@menus = Menu.new.menusPorNivel(">",session[:usuario_id])
  end

  # POST /galeria_videos
  # POST /galeria_videos.json
  def create
	@acesso=acesso(@galeria_video.Menu_id)
    @galeria_video = GaleriaVideo.new(galeria_video_params)

    respond_to do |format|
      if @galeria_video.save
        format.html { redirect_to @galeria_video, notice: 'Galeria video was successfully created.' }
        format.json { render :show, status: :created, location: @galeria_video }
      else
        format.html { render :new }
        format.json { render json: @galeria_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeria_videos/1
  # PATCH/PUT /galeria_videos/1.json
  def update
	@acesso=acesso(@galeria_video.Menu_id)
    respond_to do |format|
      if @galeria_video.update(galeria_video_params)
        format.html { redirect_to @galeria_video, notice: 'Galeria video was successfully updated.' }
        format.json { render :show, status: :ok, location: @galeria_video }
      else
        format.html { render :edit }
        format.json { render json: @galeria_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeria_videos/1
  # DELETE /galeria_videos/1.json
  def destroy
	@acesso=acesso(@galeria_video.Menu_id)
    @galeria_video.destroy
    respond_to do |format|
      format.html { redirect_to galeria_videos_url, notice: 'Galeria video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galeria_video
      @galeria_video = GaleriaVideo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galeria_video_params
      params.require(:galeria_video).permit(:nome, :descricao, :link_youtube, :Menu_id)
    end
end

app/helpers/galeria_videos_helper.rb
module GaleriaVideosHelper
end

app/views/galeria_videos/_form.html.erb
<%= form_for @galeria_video, :html => { :class => "form-horizontal galeria_video" } do |f| %>

  <% if @galeria_video.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@galeria_video.errors.count, "error") %> prohibited this galeria_video from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @galeria_video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
 <div class="form-group">
    <%= f.label :Menu_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <select class="form-control" name="galeria_video[Menu_id]" id="Menu_id">
			<%@menus.each do |menu| %>
			<option value="<%=menu.id%>" <%=(menu.id.to_s == @galeria_video.Menu_id.to_s)? "selected": "" %>><%=menu.nome%></option>
			<%end%>
		</select>
    </div>
    <%=f.error_span(:Menu_id) %>
  </div>
  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>
  <div class="form-group">
    <%= f.label :link_youtube, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :link_youtube, :class => 'form-control' %>
    </div>
    <%=f.error_span(:link_youtube) %>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
	<%if(@acesso.politica.salvar)%>	
      <%= f.submit nil, :class => 'btn btn-primary' %>
	<%end%>  
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galeria_videos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/galeria_videos/edit.html.erb
<%- model_class = GaleriaVideo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galeria_videos/index.html.erb
<%- model_class = GaleriaVideo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%if(@acesso.politica.novo)%>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_galeria_video_path,
            :class => 'btn btn-primary' %>
<%end%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:link_youtube) %></th>
      <th><%= model_class.human_attribute_name(:Menu_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @galeria_videos.each do |galeria_video| %>
      <tr>
        <td><%= link_to galeria_video.id, galeria_video_path(galeria_video) %></td>
        <td><%= galeria_video.nome %></td>
        <td><%= galeria_video.descricao %></td>
        <td><%= galeria_video.link_youtube %></td>
        <td><%= Menu.where("id=0"+galeria_video.Menu_id.to_s).first.try(:nome)   %></td>
        <td><%=l galeria_video.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      galeria_video_path(galeria_video), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_galeria_video_path(galeria_video), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      galeria_video_path(galeria_video),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/galeria_videos/new.html.erb
<%- model_class = GaleriaVideo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galeria_videos/show.html.erb
<%- model_class = GaleriaVideo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @galeria_video.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @galeria_video.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link_youtube) %>:</strong></dt>
  <dd><%= @galeria_video.link_youtube %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Menu_id) %>:</strong></dt>
  <dd><%= Menu.where("id=0"+galeria_video.Menu_id.to_s).first.try(:nome)   %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              galeria_videos_path, :class => 'btn btn-default'  %>
<%if(@acesso.politica.editar)%>			  
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_galeria_video_path(@galeria_video), :class => 'btn btn-default' %>
<%end%>
<%if(@acesso.politica.excluir)%>			  
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              galeria_video_path(@galeria_video),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<%end%>