config/routes.rb
Rails.application.routes.draw do  
  match 'w2ui/index',                  to: 'w2ui#index'           , via: [:get, :post]        
  #match '/adm/:model/lib/*pages',              to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:id/*pages',              to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:action/*pages',          to: 'w2ui#file_assets'        , via: [:get, :post]
  #match '/adm/:model/:action/:id/*pages',      to: 'w2ui#file_assets'        , via: [:get, :post]
  scope '/adm' do
    get   '/acesso_restrito',                  to: 'adm#acesso_restrito'
    get   '/tempo_sessao',                     to: 'adm#tempo_sessao'       
    get   '/senha_trocada_com_sucesso',        to: 'adm#senha_trocada_com_sucesso'  
    match '/',                                 to: 'adm#login'            , via: [:get, :post]
    match '/painel',                           to: 'adm#painel'           , via: [:get, :post]
    match '/esqueceu_a_senha',                 to: 'adm#esqueceu_a_senha'     , via: [:get, :post]
    match '/codigo_verificacao',               to: 'adm#codigo_verificacao'     , via: [:get, :post]
    match '/trocar_senha',                     to: 'adm#trocar_senha'       , via: [:get, :post]
    match '/cadastre_se',                      to: 'adm#cadastre_se'        , via: [:get, :post]
  match '/politicas',                        to: 'politicas#index'        , via: [:get, :post]
  match '/perfis_usuarios',                  to: 'perfis_usuarios#index'      , via: [:get, :post]
    resources :usuarios
    resources :perfis
    resources :menus
    resources :sistemas
    resources :galeria_fotos
    resources :galeria_videos
    resources :noticias
    resources :noticia_fotos
    resources :noticia_videos
  end
  match '*pages',                              to: 'w2ui#file_assets'				, via: [:get, :post]
end

app/models/galeria_foto.rb
class GaleriaFoto < ApplicationRecord
  belongs_to :Menu
  has_attached_file :foto, styles: 		{ tela_cheia: "1024x768>",            grande: "640x480>",			media: "320x240>",			pequena: "160x120>", 			ico: "32x32#" },
					convert_options: 	{ tela_cheia: "-quality 75 -strip",   grande: "-quality 75 -strip", media: "-quality 75 -strip",pequena: "-quality 75 -strip", 	ico: "-quality 75 -strip"},
					default_url: "/assets/img/sem_foto.png"
  validates_attachment_content_type :foto, content_type: ['image/jpg', 'image/png'] ,size: {in: 0..10.megabytes }					
  validates :foto, dimensions: { width:  160, height: 120 }
  def galeriaPermitirdaPorMenuUsuario(_usuario_id)
	return GaleriaFoto.select("galeria_fotos.*,menus.nome as menu")
	.joins(:Menu)
	.joins("inner JOIN Politicas ON (Politicas.menu_id= menus.id)")
	.joins("inner JOIN perfis ON (politicas.perfil_id= perfis.id)")
	.joins("inner JOIN perfis_usuarios ON perfis_usuarios.perfil_id=perfis.id")
	.joins("inner JOIN usuarios on (usuarios.id=perfis_usuarios.usuario_id and usuarios.id=0"+_usuario_id.to_s+")")
	.group(:id)
  end
end

app/controllers/galeria_fotos_controller.rb
class GaleriaFotosController < ApplicationController
  before_action :set_galeria_foto, only: [:show, :edit, :update, :destroy]

  # GET /galeria_fotos
  # GET /galeria_fotos.json
  def index
	  @acesso=acesso(nil)
    @galeria_fotos=GaleriaFoto.new.galeriaPermitirdaPorMenuUsuario(session[:usuario_id]) 
  end

  # GET /galeria_fotos/1
  # GET /galeria_fotos/1.json
  def show
    @menus = Menu.new.menusPorNivel(">",session[:usuario_id])
	  @acesso=acesso(@galeria_foto.Menu_id)
  end

  # GET /galeria_fotos/new
  def new
	  @acesso=acesso(nil)
	  @menus = Menu.new.menusPorNivel(">",session[:usuario_id])
    @galeria_foto = GaleriaFoto.new
  end

  # GET /galeria_fotos/1/edit
  def edit
	  @acesso=acesso(@galeria_foto.try(:Menu_id))
	  @menus = Menu.new.menusPorNivel(">",session[:usuario_id])
  end

  # POST /galeria_fotos
  # POST /galeria_fotos.json
  def create
    @menus = Menu.new.menusPorNivel(">",session[:usuario_id])
	  @acesso=acesso(@galeria_foto.try(:Menu_id))
    @galeria_foto = GaleriaFoto.new(galeria_foto_params)

    respond_to do |format|
      if @galeria_foto.save
        format.html { redirect_to @galeria_foto, notice: 'Galeria foto was successfully created.' }
        format.json { render :show, status: :created, location: @galeria_foto }
      else
        format.html { render :new }
        format.json { render json: @galeria_foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeria_fotos/1
  # PATCH/PUT /galeria_fotos/1.json
  def update
    @menus = Menu.new.menusPorNivel(">",session[:usuario_id])
	  @acesso=acesso(@galeria_foto.Menu_id)
    respond_to do |format|
      if @galeria_foto.update(galeria_foto_params)
        format.html { redirect_to @galeria_foto, notice: 'Galeria foto was successfully updated.' }
        format.json { render :show, status: :ok, location: @galeria_foto }
      else
        format.html { render :edit }
        format.json { render json: @galeria_foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeria_fotos/1
  # DELETE /galeria_fotos/1.json
  def destroy
	@acesso=acesso(@galeria_foto.Menu_id)
    @galeria_foto.destroy
    respond_to do |format|
      format.html { redirect_to galeria_fotos_url, notice: 'Galeria foto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galeria_foto
      @galeria_foto = GaleriaFoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galeria_foto_params
      params.require(:galeria_foto).permit(:nome, :descricao, :Menu_id,:foto)
    end 
end

app/helpers/galeria_fotos_helper.rb
module GaleriaFotosHelper
end

app/views/galeria_fotos/_form.html.erb
<div id="exploer">
<%= form_for @galeria_foto, :html => { :class => "form-horizontal galeria_foto" } do |f| %>

  <% if @galeria_foto.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@galeria_foto.errors.count, "error") %> prohibited this galeria_foto from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @galeria_foto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :Menu_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <select class="form-control" name="galeria_foto[Menu_id]" id="Menu_id">
			<%@menus.each do |menu| %>
			<option value="<%=menu.id%>" <%=(menu.id.to_s == @galeria_foto.Menu_id.to_s)? "selected": "" %>><%=menu.nome%></option>
			<%end%>
		</select>
    </div>
    <%=f.error_span(:Menu_id) %>
  </div>
  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>
  <div class="form-group">
    <%= f.label :foto, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :foto,:id=>"fileselect", :class => 'form-control' %>
    </div>
    <%=f.error_span(:foto) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel',:id=>"submitbutton", :default => t("helpers.links.cancel")),
                galeria_fotos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
</div>

app/views/galeria_fotos/edit.html.erb
<%- model_class = GaleriaFoto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galeria_fotos/index.html.erb
<%- model_class = GaleriaFoto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%if(@acesso.politica.novo)%>	
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_galeria_foto_path,
            :class => 'btn btn-primary' %>
<%end%>		
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:Menu_id) %></th>
      <th><%= model_class.human_attribute_name(:foto) %></th>
	  <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @galeria_fotos.each do |galeria_foto| %>
      <tr>
        <td><%= link_to galeria_foto.id, galeria_foto_path(galeria_foto) %></td>
        <td><%= galeria_foto.nome %></td>
        <td><%= galeria_foto.descricao %></td>
        <td><%= Menu.where("id=0"+galeria_foto.Menu_id.to_s).first.try(:nome) %></td>
		<td><%= image_tag galeria_foto.foto.url(:pequena), size: "160x120"%></td>  
		<td><%=l galeria_foto.created_at %></td>
        <td>
		<%if(@acesso.politica.ver)%>	
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      galeria_foto_path(galeria_foto), :class => 'btn btn-default btn-xs' %>
		<%end%>
		<%if(@acesso.politica.editar)%>	
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_galeria_foto_path(galeria_foto), :class => 'btn btn-default btn-xs' %>
		<%end%>
		<%if(@acesso.politica.excluir)%>	
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      galeria_foto_path(galeria_foto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
		<%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/galeria_fotos/new.html.erb
<%- model_class = GaleriaFoto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galeria_fotos/show.html.erb
<%- model_class = GaleriaFoto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @galeria_foto.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @galeria_foto.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Menu_id) %>:</strong></dt>
  <dd><%= Menu.where("id=0"+@galeria_foto.Menu_id.to_s).first.try(:nome)   %></dd>
  <dt><strong><%= model_class.human_attribute_name(:foto) %>:</strong></dt>
  <dd><%= image_tag @galeria_foto.foto.url(:pequena), size: "160x120"%></dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
              galeria_fotos_path, :class => 'btn btn-default'  %>
<%if(@acesso.politica.editar)%>	
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_galeria_foto_path(@galeria_foto), :class => 'btn btn-default' %>
<%end%>			  
<%if(@acesso.politica.excluir)%>	
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              galeria_foto_path(@galeria_foto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<%end%>			  